name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniforge-variant: Mambaforge
          python-version: 3.8

      - name: Create conda environment
        run: conda env create -f environment.yml

      - name: Activate conda environment
        run: |
          source $CONDA/../etc/profile.d/conda.sh
          conda activate <your-env-name>
          conda info

      - name: Install ruff
        run: |
          source $CONDA/../etc/profile.d/conda.sh
          conda activate <your-env-name>
          conda install -c conda-forge ruff

      - name: Lint with ruff
        run: |
          source $CONDA/../etc/profile.d/conda.sh
          conda activate <your-env-name>
          ruff .
